<?php

Class Reportes_model extends Model {
    
    public function __construct() {
      $this->db = parent::getInstance('MYSQL-LAB'); 
    }

    public function topExamen($FECHAINI,$FECHAFIN) {
    return  $this->db->select('P.CODREF_PRO,P.NOM_PRO ,P.COD_PRO, COUNT(P.COD_PRO) CANT'
    ,'PRODUCTO P , ORDEN O , DETALLE_ORDEN D',
    "P.COD_PRO=D.COD_PRO 
AND D.ID_ORD= O.ID_ORD  
AND P.CAT_PRO='E'
AND (DATE(O.FECRES_ORD) BETWEEN  DATE('$FECHAINI') AND DATE('$FECHAFIN'))
GROUP BY P.COD_PRO", PDO::FETCH_NUM);
}

    public function examen_doctor($FECHAINI,$FECHAFIN) {
    return  $this->db->select("P.CODREF_PRO,P.NOM_PRO ,P.COD_PRO,
COUNT(P.COD_PRO) CANT,
 (SELECT NOM_CIR FROM CIRCUITO WHERE COD_CIR=O.COD_CIR) CIRCUITO
  ,(SELECT CONCAT(PRINOM_USU,' ' ,SEGNOM_USU, ' ',PRIAPE_USU,' ',SEGAPE_USU) FROM USUARIO WHERE CED_USU=O.COD_USUCRE) DOCTOR"
    ,'PRODUCTO P , ORDEN O , DETALLE_ORDEN D',
    "P.COD_PRO=D.COD_PRO
 AND D.ID_ORD= O.ID_ORD AND P.CAT_PRO='E' AND (DATE(O.FECRES_ORD)
 BETWEEN DATE('2016-01-01') AND DATE('2016-12-31'))
 
GROUP BY P.COD_PRO ,
 (SELECT CONCAT(PRINOM_USU,' ' ,SEGNOM_USU, ' ',PRIAPE_USU,' ',SEGAPE_USU) FROM USUARIO WHERE CED_USU=O.COD_USUCRE)", PDO::FETCH_NUM);
} 
}